import { StyleSheet } from 'react-native';

export const F = { sm: 13, md: 16, lg: 22 };

export const estilos = (c) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg },
    resumen: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 4 },
    resumenText: { fontSize: F.sm, color: c.textSub },
    resumenNum: { fontWeight: '700', color: c.primary },
    searchRow: { padding: 12, paddingBottom: 0 },
    search: {
      backgroundColor: c.surface,
      borderWidth: 1.5,
      borderColor: c.border,
      borderRadius: 0,
      padding: 10,
      fontSize: F.md,
      color: c.text,
    },
    filtersRow: { marginTop: 8 },
    filtersContent: {
      paddingHorizontal: 12,
      gap: 8,
      alignItems: 'center',
      paddingVertical: 4,
    },
    filterChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 0,
      borderWidth: 1.5,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    filterChipActive: { backgroundColor: c.primary, borderColor: c.primary },
    filterChipText: { fontSize: F.sm, color: c.textSub },
    filterChipTextActive: { color: '#fff', fontWeight: '600' },
    filterDivider: { width: 1, height: 24, backgroundColor: c.border },
    actionsRow: { flexDirection: 'row', gap: 8, padding: 12, paddingTop: 8 },
    actionChip: {
      flex: 1,
      padding: 8,
      borderRadius: 0,
      borderWidth: 1.5,
      borderColor: c.border,
      alignItems: 'center',
    },
    actionChipText: { fontSize: F.sm, color: c.textSub },
    seccion: { marginBottom: 8 },
    seccionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderBottomWidth: 2,
      borderBottomColor: c.text,
    },
    seccionEmoji: { fontSize: F.md, marginRight: 6 },
    seccionNombre: {
      flex: 1,
      fontSize: F.sm,
      fontWeight: '800',
      color: c.text,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    seccionContador: {
      fontSize: F.sm,
      fontWeight: '800',
      color: c.primary,
      borderBottomWidth: 2,
      borderBottomColor: c.primary,
      marginRight: 6,
    },
    seccionContadorVacio: {
      color: c.textMuted,
      borderBottomColor: c.textMuted,
    },
    seccionArrow: { fontSize: 10, color: c.textMuted },
    emptyContainer: { alignItems: 'center', marginTop: 80 },
    emptyIcon: { fontSize: 56, marginBottom: 16 },
    emptyText: {
      fontSize: F.md,
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 26,
    },
    fab: {
      position: 'absolute',
      bottom: 28,
      right: 24,
      width: 58,
      height: 58,
      borderRadius: 0,
      borderWidth: 2,
      borderColor: c.text,
      backgroundColor: c.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    fabText: { color: '#fff', fontSize: 30, lineHeight: 34 },
    modalOverlay: {
      flex: 1,
      backgroundColor: '#00000088',
      justifyContent: 'flex-end',
    },
    modalBox: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderTopWidth: 2,
      borderColor: c.border,
      padding: 24,
      maxHeight: '92%',
    },
    modalHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    modalTitulo: {
      fontSize: F.lg,
      fontWeight: '800',
      letterSpacing: 0.5,
      color: c.text,
    },
    cerrarBtn: { fontSize: F.md, color: c.textMuted, paddingHorizontal: 4 },
    limpiarFiltro: { color: c.danger, fontSize: F.sm },
    catRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 0,
      marginBottom: 2,
    },
    catRowEmoji: { fontSize: F.lg, marginRight: 12 },
    catRowNombre: { flex: 1, fontSize: F.md, color: c.text },
    label: {
      fontSize: F.sm,
      color: c.textSub,
      marginBottom: 6,
      marginTop: 12,
      fontWeight: '800',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    input: {
      backgroundColor: c.surfaceAlt,
      borderWidth: 1.5,
      borderColor: c.border,
      borderRadius: 0,
      padding: 12,
      fontSize: F.md,
      color: c.text,
    },
    dropdown: {
      backgroundColor: c.surfaceAlt,
      borderWidth: 1.5,
      borderColor: c.border,
      borderRadius: 0,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    dropdownText: { flex: 1, fontSize: F.md, color: c.text },
    dropdownArrow: { fontSize: F.sm, color: c.textMuted },
    modalBtns: { flexDirection: 'row', gap: 12, marginTop: 20 },
    btnCancel: {
      flex: 1,
      padding: 14,
      borderRadius: 0,
      borderWidth: 2,
      borderColor: c.border,
      alignItems: 'center',
    },
    btnCancelText: { fontSize: F.md, color: c.text },
    btnSave: {
      flex: 1,
      padding: 14,
      borderRadius: 0,
      backgroundColor: c.primary,
      alignItems: 'center',
    },
    btnApply: {
      flex: 1,
      padding: 14,
      borderRadius: 0,
      minHeight: 48,
      backgroundColor: c.primary,
      alignItems: 'center',
    },
    btnSaveText: { fontSize: F.md, color: '#fff', fontWeight: '700' },
    headerBtns: { flexDirection: 'row', gap: 4 },
    headerBtn: { paddingHorizontal: 8, paddingVertical: 4 },
    headerBtnText: { fontSize: 20 },
    headerBtnActivo: {
      backgroundColor: c.primary,
      borderWidth: 2,
      borderColor: c.text,
    },
    compraBar: {
      padding: 16,
      paddingBottom: 12,
      borderBottomWidth: 2,
      borderBottomColor: c.text,
      backgroundColor: c.surface,
    },
    compraTitulo: {
      fontSize: F.sm,
      fontWeight: '800',
      letterSpacing: 1,
      color: c.textSub,
    },
    compraNum: {
      fontSize: F.lg,
      fontWeight: '800',
      color: c.text,
      marginTop: 2,
    },
    compraTrack: {
      height: 8,
      marginTop: 10,
      borderWidth: 1.5,
      borderColor: c.text,
    },
    compraFill: { height: '100%', backgroundColor: c.primary },
    finContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 32,
    },
    finEmoji: { fontSize: 72, marginBottom: 16 },
    finTitulo: {
      fontSize: F.lg,
      fontWeight: '800',
      color: c.text,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 24,
    },
    ordenRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      backgroundColor: c.surface,
      borderBottomWidth: 1.5,
      borderBottomColor: c.border,
    },
    ordenRowActiva: { borderWidth: 2, borderColor: c.primary, zIndex: 10 },
    ordenHandle: { fontSize: F.lg, color: c.textMuted, paddingHorizontal: 12 },
    ordenAyuda: { fontSize: F.sm, color: c.textMuted, marginBottom: 12 },
  });

export const estilosItem = (c) =>
  StyleSheet.create({
    swipeAccion: {
      width: 72,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: c.danger,
    },
    swipeAccionText: { fontSize: F.lg },
    item: {
      backgroundColor: c.surface,
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 1.5,
      borderColor: c.border,
    },
    itemChecked: { backgroundColor: c.checked, borderColor: c.border },
    itemMain: { flexDirection: 'row', alignItems: 'center', padding: 12 },
    itemEmoji: { fontSize: 28, marginRight: 12 },
    itemInfo: { flex: 1 },
    itemNombre: { fontSize: F.md, fontWeight: '700', color: c.text },
    itemNombreChecked: {
      color: c.checkedText,
      textDecorationLine: 'line-through',
    },
    itemNotas: { fontSize: F.sm, color: c.textMuted, marginTop: 2 },
    itemRight: { alignItems: 'flex-end', gap: 2 },
    itemCantidad: { fontSize: F.sm, fontWeight: '600', color: c.textSub },
    itemAutor: { fontSize: 11, color: c.textMuted },
    // Modo compra: filas más grandes
    itemMainGrande: { paddingVertical: 20, paddingHorizontal: 16 },
    itemEmojiGrande: { fontSize: 36, marginRight: 16 },
    itemNombreGrande: { fontSize: 20 },
    itemCantidadGrande: { fontSize: F.md },
    checkmark: {
      position: 'absolute',
      right: 12,
      fontSize: F.md,
      color: c.primary,
    },
  });
